name: Aquamarine
description: A ticket plugin for Xeno
author: Xeno
website: https://xeno.fi/
commands:
  ticket:
    description: Open a new ticket
    aliases: [apupyyntö, avunpyyntö, tiketti, helpop]
    permission: aquamarine.ticket
  tickets:
    description: Show a list of your recent tickets
    aliases: [apupyynnöt, avunpyynnöt, tiketit]
    permission: aquamarine.ticket
  xt:
    description: Staff features
    aliases: [aq]
    permission: aquamarine.staff
  xti:
    description: Staff features
    aliases: [aqi]
    permission: aquamarine.staff
permissions:
  aquamarine.ticket:
    description: Permission to open new tickets
  aquamarine.staff:
    description: Permission to teleport to tickets and solve them
version: 0.1.0
main: fi.xeno.aquamarine.XTicketsPlugin
